# serverless.yml
findmystuff:
  component: "@sls-next/serverless-component@3.7"
  inputs:
    memory:
      defaultLambda: 1024
      apiLambda: 2048
      imageLambda: 2048
    runtime:
      defaultLambda: "nodejs14.x"
      apiLambda: "nodejs14.x"
      imageLambda: "nodejs14.x"
    timeout:
      defaultLambda: 30
      apiLambda: 30
      imageLambda: 30
