import Head from 'next/head'


export async function getServerSideProps(context) {
  return {
    props: {
      ssr : "Hello SSR"
    }, // will be passed to the page component as props
  }
}

export default function Home({ssr}) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=''>
        {ssr}
      </main>

    </div>
  )
}
